name: ScoreboardNameRestore
version: '${project.version}'
main: org.funty.scoreboardnamerestore.Main
api-version: '1.20'
author: 'Funty'
commands:
  ScoreRestore:
    permissions: 'scoreboardnamerestore.scorerestore'
  PlayerInfo:
    permission: 'scoreboardnamerestore.playerinfo.use'